In [2]:
from weights import *
from db_functions import *
import numpy as np

In [3]:
request_frame = {'article_id': [1011,1019,1022],
        'duration': [120,300,50]
        }


In [4]:
local_id = get_local_id(request_frame['article_id'])

MySQL connection is closed


In [5]:
local_id

local_id
0         0
1         1
2         4

In [6]:
# GET MAGNITUDE
# GET THETA
# GET EUCLIDEAN

In [80]:
def get_angles_query():
    sql = """
    SELECT * FROM `recen_theta_content` 
    WHERE local_id IN (%s)
    """
    return sql

def get_vector_magnitude_query():
    sql = """ 
    SELECT * FROM `recen_magnitude_content` WHERE local_id in (%s)
    """
    return sql


def get_euclidean_distance_query():
    sql = """
    SELECT * FROM `recen_distance_content` WHERE local_id in (%s)
    """
    return sql

In [81]:
def get_magnitude_diff_squares(local_id):
    
    id_string = ''
    for index, row in local_id.iterrows():
        if index > 0:
            id_string += ', '
        id_string += str(row['local_id'])
    
    conn = pymysql.connect(**connection_properties)
    cursor = conn.cursor()
    sql = get_vector_magnitude_query() % id_string
    
    try:
        df = pd.read_sql(sql, conn)
        
        if(conn.open):
           conn.close()
           print("MySQL connection is closed")

        return df

    except Exception as e :
        print ("Error while connecting to MySQL", e)

In [82]:
def get_angles(local_id):
    
    id_string = ''
    for index, row in local_id.iterrows():
        if index > 0:
            id_string += ', '
        id_string += str(row['local_id'])

    conn = pymysql.connect(**connection_properties)
    cursor = conn.cursor()
    sql = get_angles_query() % id_string
    
    try:
        df = pd.read_sql(sql, conn)
        
        if(conn.open):
           conn.close()
           print("MySQL connection is closed")

        return df

    except Exception as e :
        print ("Error while connecting to MySQL", e)

In [83]:
def get_euclidean_distance(local_id):
    id_string = ''
    for index, row in local_id.iterrows():
        if index > 0:
            id_string += ', '
        id_string += str(row['local_id'])

    conn = pymysql.connect(**connection_properties)
    cursor = conn.cursor()
    sql = get_euclidean_distance_query() % id_string
    
    try:
        df = pd.read_sql(sql, conn)
        
        if(conn.open):
           conn.close()
           print("MySQL connection is closed")

        return df

    except Exception as e :
        print ("Error while connecting to MySQL", e)

In [90]:
angles = get_angles(local_id)
vector_magnitude_diff_square = get_magnitude_diff_squares(local_id)
euclidean_distance = get_euclidean_distance(local_id)

MySQL connection is closed
MySQL connection is closed
MySQL connection is closed


In [91]:
theta = angles['angle'].apply(lambda row: pd.read_json(row, typ = 'list'))
theta = theta.to_numpy()
theta

array([[0.17453307, 1.64065636, 1.66231963, ..., 1.6228282 , 1.57071232,
        1.48819868],
       [1.64065636, 0.17453293, 1.52651255, ..., 1.73201808, 1.71839626,
        1.65638284],
       [1.69830733, 1.627189  , 1.58576619, ..., 1.72853246, 1.73824021,
        1.70057063]])

In [97]:
diff_square = vector_magnitude_diff_square['magnitude_diff_square'].apply(lambda row: pd.read_json(row, typ = 'list'))
diff_square = diff_square.to_numpy()
diff_square

array([[    0.        ,  3575.36828211,  4271.06747212, ...,
        10693.53265857,  7610.99490176, 11039.27175804],
       [ 3575.36828211,     0.        ,    30.90271532, ...,
         1902.28175981,   753.31765209,  2049.69481921],
       [ 5501.68020375,   206.75358686,    77.79076823, ...,
          854.75694526,   170.76489382,   954.47796733]])

In [98]:
distances = euclidean_distance['distance'].apply(lambda row: pd.read_json(row, typ = 'list'))
distances = distances.to_numpy()
distances

array([[  0.        , 137.86974857, 137.0264865 , ..., 126.74526777,
        126.77152799, 123.63912415],
       [137.86974857,   0.        ,  81.25884899, ...,  71.4583223 ,
         77.72380463,  69.31166048],
       [135.76761662,  80.98986037,  75.08033795, ...,  58.03955817,
         66.47566765,  56.81683291]])

In [99]:
diff_square + distances

array([[    0.        ,  3713.23803068,  4408.09395862, ...,
        10820.27792635,  7737.76642975, 11162.91088219],
       [ 3713.23803068,     0.        ,   112.16156431, ...,
         1973.74008211,   831.04145671,  2119.00647969],
       [ 5637.44782037,   287.74344723,   152.87110618, ...,
          912.79650343,   237.24056147,  1011.29480024]])

In [108]:
magnitudes.to_numpy()

array([[list([[127.4188473234]])],
       [list([[67.6244639575]])],
       [list([[62.0654428818]])],
       [list([[143.2048138668]])],
       [list([[53.2455353861]])],
       [list([[46.6373914753]])],
       [list([[58.5571806358]])],
       [list([[105.5725344669]])],
       [list([[248.1236070731]])],
       [list([[62.7827711249]])],
       [list([[150.3658741472]])],
       [list([[79.7224374518]])],
       [list([[86.7795323135]])],
       [list([[130.6969114575]])],
       [list([[133.2632752841]])],
       [list([[174.0766796029]])],
       [list([[77.7718456771]])],
       [list([[221.9465839689]])],
       [list([[130.8099157291]])],
       [list([[166.5842859348]])],
       [list([[123.9461781888]])],
       [list([[143.63853033]])],
       [list([[84.9090632799]])],
       [list([[124.1266416915]])],
       [list([[87.2993855175]])],
       [list([[79.7147115956]])],
       [list([[108.120253388]])],
       [list([[119.472897368]])],
       [list([[73.5255182087]])],
  

In [ ]:
def get_euclidean_distance(local_id)

In [ ]:
def get_ts_ss_similarity(article_id):

In [ ]:
def get_triangle_similarity(magnitude, angles):

In [33]:
import numpy as np
from sklearn.metrics import pairwise_distances
from sklearn.metrics.pairwise import pairwise_kernels

X = np.array([[2, 3], [3, 5], [5, 8]])
Y = np.array([[1, 0], [2, 1]])

In [34]:
X

array([[2, 3],
       [3, 5],
       [5, 8]])

In [35]:
Y

array([[1, 0],
       [2, 1]])

In [36]:
pairwise_distances(Y, Y, metric='manhattan')

array([[0., 2.],
       [2., 0.]])

In [37]:
pairwise_distances(X, X, metric='manhattan')

array([[0., 3., 8.],
       [3., 0., 5.],
       [8., 5., 0.]])

In [32]:

pairwise_distances(X, Y, metric='manhattan')



pairwise_distances(X, metric='manhattan')



pairwise_kernels(X, Y, metric='linear')

array([[ 2.,  7.],
       [ 3., 11.],
       [ 5., 18.]])

In [59]:
p = np.array([[1,2,5], [2,3,4], [1,2,9]])
p

array([[1, 2, 5],
       [2, 3, 4],
       [1, 2, 9]])

In [60]:
p.shape

(3, 3)

In [61]:
pairwise_distances(p, metric='manhattan')

array([[0., 3., 4.],
       [3., 0., 7.],
       [4., 7., 0.]])

In [62]:
pairwise_kernels(p, metric='linear')

array([[30., 28., 50.],
       [28., 29., 44.],
       [50., 44., 86.]])

In [66]:
Y

array([[1, 0],
       [2, 1]])

In [64]:
np.square(Y)

array([[1, 0],
       [4, 1]])

In [100]:
df = pd.DataFrame({"A": [1, 2], "B": [3, 4]})
type(df)

pandas.core.frame.DataFrame

In [101]:
df.to_numpy()

array([[1, 3],
       [2, 4]])

In [3]:
import numpy as np
a = np.arange(0, 9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
m = np.array([[0], [1], [2], [3], [4], [5], [6], [7], [8]])
type(m)

numpy.ndarray

In [16]:
import pandas
DataFrame(m)

NameError: name 'DataFrame' is not defined

In [66]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Aug 20 18:00:07 2019

@author: smkj33
"""



"""
Previous Version: 
    bkp_model_20_Aug.py

-- Removing html filter using HTML.parser 
-- Removing related import statement
-- Beautiful soup will be used in it's place'


    bkp_model_19_Oct.py 
    
--  Replaced Potter Stemmer with Snowball Stemmer
--  Added Cosine similarity with TS-SS.

"""


import pandas as pd
import re
import math
from bs4 import BeautifulSoup

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer


from nltk.tokenize import sent_tokenize, word_tokenize
# from nltk.stem import PorterStemmer
from porter2stemmer import Porter2Stemmer

from sklearn.metrics.pairwise import linear_kernel
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics.pairwise import euclidean_distances
from sklearn.metrics import pairwise_distances



from db_functions import *
from queries import *





#-------------------------------------#
# MODEL CREATE HELPER FUNCTIONS
#-------------------------------------#



def filter_html(text):
    soup = BeautifulSoup(text, features="html5lib")
    # text = re.sub('[^a-z\s]', '',soup.get_text(separator=' ').lower())
    text = soup.get_text(separator=' ')
    return text


def text_stemmer (txt, stemmer):
    token_words=word_tokenize(txt)
    stem_sentence=[]
    for word in token_words:
        stem_sentence.append(stemmer.stem(word))
        stem_sentence.append(" ")
    return "".join(stem_sentence)


def clean_tags(x):
    if isinstance(x, str):
        return str.lower(x.replace(" ", "")).replace(","," ")

    else:
        return ''


def theta(cosine_similarity):
    sim = np.divide(np.trunc(np.multiply(cosine_similarity, 100000000000000)), 100000000000000)
    angles = np.arccos(sim) + math.radians(10)
    return angles


def magnitude_diff_square(matrix):
    magnitude = np.sqrt(matrix.multiply(matrix).sum(1))
    diff_squares = np.square(pairwise_distances(magnitude, metric='manhattan'))
    return diff_squares


def euclidean(vectors):
    distances = euclidean_distances(vectors)
    return distances


#-------------------------------------#
# MODEL EXPORT HELPER FUNCTIONS
#-------------------------------------#

def matrix_to_json(matrix):
    df = pd.DataFrame(matrix.apply(lambda row: row.to_json(), axis=1), columns = ['data_col'])
    df['local_id'] = df.index
    return df


def export_content_cosine_similarity (similarity_matrix):
    df = matrix_to_json(similarity_matrix)
    sql = export_content_cosine_similarity_query()
    export_data(df, sql)


def export_title_similarity (similarity_matrix):
    df = matrix_to_json(similarity_matrix)
    sql = export_title_similarity_query()
    export_data(df, sql)


def export_cat_tags_similarity (similarity_matrix):
    df = matrix_to_json(similarity_matrix)
    sql = export_cat_tags_similarity_query()
    export_data(df, sql)


def export_content_angles(angles):
    df = matrix_to_json(angles)
    sql = export_content_angles_query()
    export_data(df, sql)


def export_content_distance(distance):
    df = matrix_to_json(distance)
    sql = export_content_distance_query()
    export_data(df, sql)


def export_content_magnitude(vector_size):
    df = matrix_to_json(vector_size)
    df['local_id'] = df.index
    sql = export_content_magnitude_query()
    export_data(df, sql)


#-------------------------------------#
# MODEL CREATE DRIVER
#-------------------------------------#


truncate_similarities()
article_master = import_content()



## PREPROCESS CONTENT
print("Previous Model Truncated.")
print("Pre-processing....")


# REDUCE CONTENT:
article_master['reduced_content'] = article_master.apply\
    (lambda row: re.sub('[^a-z\s]', '',filter_html(row.bodytext).lower()), axis = 1)

#-- Potential Global Variable

snowball = Porter2Stemmer()

article_master['stemmed_content'] = article_master.apply\
    (lambda row: text_stemmer(row.reduced_content, snowball), axis = 1)

article_master['stemmed_content'] = article_master['stemmed_content'].fillna('')



# REDUCE TITLE:
# It must be noted that numbers are removed from the content and not from the title
article_master['reduced_title'] = article_master.apply\
    (lambda row: re.sub('[^a-z0-9\s]', '',row.title.lower()), axis = 1)

article_master['stemmed_title'] = article_master.apply\
    (lambda row: text_stemmer(row.reduced_title, snowball), axis = 1)



# REDUCE TAGS AND CATEGORY
article_master['reduced_category'] = article_master['category'].apply(clean_tags)
article_master['reduced_tags'] = article_master['tags'].apply(clean_tags)
article_master["meta_soup"] = article_master["reduced_category"] + ' ' + article_master['reduced_tags']



#-------------------------------------#
## Preprocess Content - End
#-------------------------------------#

print("Creating new Model.")

# MODEL CREATION

# Define a TF-IDF Vectorizer Object for Un-normalised TF-IDF vectors
# Remove all english stop words such as 'the', 'a'


tfidf = TfidfVectorizer(stop_words = 'english', norm = None)
tfidf_vectors = tfidf.fit_transform(article_master['stemmed_content'])


cosine_sim_content = cosine_similarity(tfidf_vectors)

# Export content similarity matrix
df = pd.DataFrame.from_records(cosine_sim_content)
export_content_cosine_similarity(df)
print("Exported Content Cosine Similarity Matrix .")

# Theta, Euclidean Distance and Magnitude of TF-IDF vectors: required for TS-SS similarity
angles = theta(cosine_sim_content)
euclidean_distance = euclidean(tfidf_vectors)
diff_squares = magnitude_diff_square(tfidf_vectors)

# Export Theta matrix
df = pd.DataFrame.from_records(angles)
export_content_angles(df)

# Export Euclidean Distance  matrix
df = pd.DataFrame.from_records(euclidean_distance)
export_content_distance(df)

# Export Vector Magnitudes
df = pd.DataFrame.from_records(diff_squares)
export_content_magnitude(df)

print("Exported Content TS-SS Similarity Matrices .")

# Define a TF-IDF Vectorizer Object for normalised TF-IDF vectors
tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix_title = tfidf.fit_transform(article_master['stemmed_title'])
cosine_sim_title = linear_kernel(tfidf_matrix_title, tfidf_matrix_title)

# Export title similarity matrix
df = pd.DataFrame.from_records(cosine_sim_title)
export_title_similarity(df)
print("Exported Title Cosine Similarity Matrix .")



count = CountVectorizer(stop_words='english')
count_matrix = count.fit_transform(article_master["meta_soup"])
cosine_sim_cat_tags = cosine_similarity(count_matrix, count_matrix)

# Export title similarity matrix
df = pd.DataFrame.from_records(cosine_sim_cat_tags)
export_cat_tags_similarity(df)
print("Exported Tags/Category Cosine Similarity Matrix .")


article_map = (article_master[['article_id','title']].copy()).drop_duplicates()
article_map['local_id'] = article_map.index

# Export article_map
export_map(article_map)

print("Model Created")





MySQL connection is closed
MySQL connection is closed
Previous Model Truncated.
Pre-processing....
Creating new Model.
MySQL connection is closed
Exported Content Cosine Similarity Matrix .
MySQL connection is closed
MySQL connection is closed
Error while connecting to MySQL (1054, "Unknown column 'magnitude' in 'field list'", 'occurred at index 0')
Exported Content TS-SS Similarity Matrices .
MySQL connection is closed
Exported Title Cosine Similarity Matrix .
MySQL connection is closed
Exported Tags/Category Cosine Similarity Matrix .
MySQL connection is closed
Model Created


In [16]:
df = pd.DataFrame.from_records(cosine_sim_content)
df

0         1         2         3         4         5         6    \
0    1.000000  0.104482  0.082914  0.061083  0.047005  0.124568  0.032556   
1    0.104482  1.000000  0.217075  0.160044  0.117866  0.139348  0.193486   
2    0.082914  0.217075  1.000000  0.161446  0.158887  0.155142  0.175954   
3    0.061083  0.160044  0.161446  1.000000  0.115371  0.117243  0.111671   
4    0.047005  0.117866  0.158887  0.115371  1.000000  0.092860  0.113998   
..        ...       ...       ...       ...       ...       ...       ...   
405  0.156927  0.051357  0.058223  0.083986  0.058066  0.093286  0.019947   
406  0.338101  0.038987  0.037622  0.036157  0.033699  0.058142  0.004657   
407  0.122195  0.013311  0.014409  0.031647  0.016796  0.049888  0.019594   
408  0.173731  0.026930  0.028985  0.013316  0.007089  0.018824  0.019213   
409  0.254307  0.088829  0.071749  0.049020  0.044744  0.075193  0.048920   

          7         8         9    ...       400       401       402  \
0    0.092386  0.515766  0.057733  ...  0.071749  0.056079  0.062083   
1    0.081696  0.157214  0.144680  ...  0.064025  0.093637  0.113956   
2    0.084396  0.145292  0.283712  ...  0.068752  0.073040  0.113915   
3    0.079302  0.113797  0.134122  ...  0.107152  0.079064  0.099320   
4    0.085072  0.089066  0.098925  ...  0.078345  0.059542  0.090554   
..        ...       ...       ...  ...       ...       ...       ...   
405  0.048535  0.157856  0.043121  ...  0.085112  0.074922  0.090113   
406  0.021111  0.257348  0.039872  ...  0.039957  0.054950  0.042494   
407  0.042749  0.094910  0.013201  ...  0.018156  0.085692  0.010314   
408  0.032744  0.161852  0.014887  ...  0.014826  0.013892  0.023357   
409  0.040248  0.278119  0.033786  ...  0.034541  0.065221  0.031761   

          403       404       405       406       407       408       409  
0    0.210171  0.136310  0.156927  0.338101  0.122195  0.173731  0.254307  
1    0.034278  0.060457  0.051357  0.038987  0.013311  0.026930  0.088829  
2    0.012304  0.052209  0.058223  0.037622  0.014409  0.028985  0.071749  
3    0.035586  0.023210  0.083986  0.036157  0.031647  0.013316  0.049020  
4    0.010974  0.032596  0.058066  0.033699  0.016796  0.007089  0.044744  
..        ...       ...       ...       ...       ...       ...       ...  
405  0.059200  0.049173  1.000000  0.116099  0.141277  0.044868  0.125774  
406  0.112597  0.056337  0.116099  1.000000  0.099344  0.166259  0.174898  
407  0.095027  0.029338  0.141277  0.099344  1.000000  0.085401  0.106242  
408  0.231086  0.261538  0.044868  0.166259  0.085401  1.000000  0.353489  
409  0.176596  0.203681  0.125774  0.174898  0.106242  0.353489  1.000000  

[410 rows x 410 columns]

In [60]:
vector_magnitude = get_magnitude(tfidf_vectors)
vector_magnitude

matrix([[127.41884732],
        [ 67.62446396],
        [ 62.06544288],
        [143.20481387],
        [ 53.24553539],
        [ 46.63739148],
        [ 58.55718064],
        [105.57253447],
        [248.12360707],
        [ 62.78277112],
        [150.36587415],
        [ 79.72243745],
        [ 86.77953231],
        [130.69691146],
        [133.26327528],
        [174.0766796 ],
        [ 77.77184568],
        [221.94658397],
        [130.80991573],
        [166.58428593],
        [123.94617819],
        [143.63853033],
        [ 84.90906328],
        [124.12664169],
        [ 87.29938552],
        [ 79.7147116 ],
        [108.12025339],
        [119.47289737],
        [ 73.52551821],
        [137.45034368],
        [286.84514816],
        [105.71980945],
        [119.15650396],
        [173.21185206],
        [222.51267694],
        [107.15491292],
        [134.72858867],
        [106.94499382],
        [ 76.59605629],
        [149.54476429],
        [203.5391247 ],
        [138.892

In [63]:
magnitude_diff_square = np.square(pairwise_distances(vector_magnitude, metric='manhattan'))

In [64]:
magnitude_diff_sqaure

array([[0.00000000e+00, 3.57536828e+03, 4.27106747e+03, ...,
        1.06935327e+04, 7.61099490e+03, 1.10392718e+04],
       [3.57536828e+03, 0.00000000e+00, 3.09027153e+01, ...,
        1.90228176e+03, 7.53317652e+02, 2.04969482e+03],
       [4.27106747e+03, 3.09027153e+01, 0.00000000e+00, ...,
        1.44826934e+03, 4.79067547e+02, 1.57724424e+03],
       ...,
       [1.06935327e+04, 1.90228176e+03, 1.44826934e+03, ...,
        0.00000000e+00, 2.61421115e+02, 2.75029137e+00],
       [7.61099490e+03, 7.53317652e+02, 4.79067547e+02, ...,
        2.61421115e+02, 0.00000000e+00, 3.17799170e+02],
       [1.10392718e+04, 2.04969482e+03, 1.57724424e+03, ...,
        2.75029137e+00, 3.17799170e+02, 0.00000000e+00]])

In [19]:
vector_magnitude.shape

(410, 1)

In [27]:
df2 = pd.DataFrame(vector_magnitude)

In [28]:
df2

0
0    127.418847
1     67.624464
2     62.065443
3    143.204814
4     53.245535
..          ...
405   23.262859
406   19.705041
407   24.009309
408   40.177831
409   22.350909

[410 rows x 1 columns]

In [18]:
df1

0
0    [[[[[127.41884732]]]]]
1     [[[[[67.62446396]]]]]
2     [[[[[62.06544288]]]]]
3    [[[[[143.20481387]]]]]
4     [[[[[53.24553539]]]]]
..                      ...
405   [[[[[23.26285934]]]]]
406   [[[[[19.70504099]]]]]
407    [[[[[24.0093088]]]]]
408   [[[[[40.17783116]]]]]
409   [[[[[22.35090855]]]]]

[410 rows x 1 columns]

In [20]:
a = np.matrix('1 ; 3 ')
pd.DataFrame(a)


0
0  1
1  3

In [25]:
a.shape

(2, 1)

In [24]:
b = np.matrix([[127.41884732],
        [ 67.62446396],
        [ 62.06544288],
        [143.20481387],
        [ 53.24553539],
        [ 46.63739148],
        [ 58.55718064]])

b

matrix([[127.41884732],
        [ 67.62446396],
        [ 62.06544288],
        [143.20481387],
        [ 53.24553539],
        [ 46.63739148],
        [ 58.55718064]])

In [26]:
pd.DataFrame(b)

0
0  127.418847
1   67.624464
2   62.065443
3  143.204814
4   53.245535
5   46.637391
6   58.557181

In [23]:
df.iloc[2]

0    [[[[[62.06544288]]]]]
Name: 2, dtype: object

In [1]:
from db_functions import *
article_master = import_content()

MySQL connection is closed


In [2]:
article_master

article_id                                              title category  \
0          1011                Bridging the industrial heat divide     None   
1          1019              EUSEW 2016 - energy efficiency awards     None   
2          1020      How much can energy management actually save?     None   
3          1021  All eyes on China’s 13th Five-Year Plan for en...     None   
4          1022             EEIP at Turkish Energy Efficiency Week     None   
..          ...                                                ...      ...   
405        1627                        Shining a light on Tomatoes     None   
406        1628          Gothenborg Energi sees the bigger Picture     None   
407        1629    Clean Power when ORC System recovers Waste Heat     None   
408        1630  Significant cost savings & lowered CO2 Emissio...     None   
409        1631  ORC-systems are helping to create a sustainabl...     None   

     tags                                           bodytext  
0    None  <p>Between industrial heat owners and relevant...  
1    None  <p>Three energy efficiency and renewable energ...  
2    None  <p>There’s no debate on the importance of the ...  
3    None  <p>China’s 13th&nbsp;Five-Year Plan for energy...  
4    None  <p>EEIP is proud to announce that two of our B...  
..    ...                                                ...  
405  None  Royal Pride Holland is using the J624 GS engin...  
406  None  <p>The heat recovery block station at the car ...  
407  None  Generating clean power in Japanese incineratio...  
408  None  Marc Delannoy, General Manager Airflux: “Airfl...  
409  None  <p>ORC (Organic Rankine Cycle) technology made...  

[410 rows x 5 columns]