In [5]:
from weights import *
from db_functions import *
import numpy as np

In [12]:
request_frame = {'article_id': [1011,1019,1022],
        'duration': [120,300,50]
        }


In [7]:
local_id = get_local_id(request_frame['article_id'])

MySQL connection is closed


In [8]:
local_id

local_id
0         0
1         1
2         4

In [9]:
# GET MAGNITUDE
# GET THETA
# GET EUCLIDEAN

In [26]:
def get_angles_query():
    sql = """
    SELECT * FROM `recen_theta_content` 
    WHERE local_id IN (%s)
    """
    return sql

def get_vector_magnitude_query():
    sql = """ SELECT * FROM `recen_magnitude_content` """
    return sql


def get_euclidean_distance_query():
    sql = """
    SELECT * FROM `recen_distance_content` WHERE local_id in (%s)
    """
    return sql

In [21]:
def get_vector_magnitude():
    
    conn = pymysql.connect(**connection_properties)
    cursor = conn.cursor()
    sql = get_vector_magnitude_query()
    
    try:
        df = pd.read_sql(sql, conn)
        
        if(conn.open):
           conn.close()
           print("MySQL connection is closed")

        return df

    except Exception as e :
        print ("Error while connecting to MySQL", e)

In [28]:
def get_angles(local_id):
    id_string = ''
    for index, row in local_id.iterrows():
        if index > 0:
            id_string += ', '
        id_string += str(row['local_id'])

    conn = pymysql.connect(**connection_properties)
    cursor = conn.cursor()
    sql = get_angles_query() % id_string
    
    try:
        df = pd.read_sql(sql, conn)
        
        if(conn.open):
           conn.close()
           print("MySQL connection is closed")

        return df

    except Exception as e :
        print ("Error while connecting to MySQL", e)

In [29]:
def get_euclidean_distance(local_id):
    id_string = ''
    for index, row in local_id.iterrows():
        if index > 0:
            id_string += ', '
        id_string += str(row['local_id'])

    conn = pymysql.connect(**connection_properties)
    cursor = conn.cursor()
    sql = get_euclidean_distance_query() % id_string
    
    try:
        df = pd.read_sql(sql, conn)
        
        if(conn.open):
           conn.close()
           print("MySQL connection is closed")

        return df

    except Exception as e :
        print ("Error while connecting to MySQL", e)

In [72]:
angles = get_angles(local_id)
vector_magnitude = get_vector_magnitude()
euclidean_distance = get_euclidean_distance(local_id)

MySQL connection is closed
MySQL connection is closed
MySQL connection is closed


In [102]:
distances = euclidean_distance['distance'].apply(lambda row: pd.read_json(row, typ = 'list'))
distances = distances.to_numpy()

In [73]:
euclidean_distance

local_id                                           distance
0         0  {"0": 0, "1": 137.8697485665, "2": 137.0264865...
1         1  {"0": 137.8697485665, "1": 0, "2": 81.25884898...
2         4  {"0": 135.7676166219, "1": 80.9898603678, "2":...

In [75]:
type(euclidean_distance)

pandas.core.frame.DataFrame

In [71]:
euclidean_distance.shape

(3, 3)

In [89]:
distances = euclidean_distance['distance'].apply(lambda row: pd.read_json(row, typ = 'list'))
distances

0           1           2           3           4           5    \
0    0.000000  137.869749  137.026487  185.779479  135.767617  130.115800   
1  137.869749    0.000000   81.258849  148.259563   80.989860   76.610422   
2  135.767617   80.989860   75.080338  146.912525    0.000000   67.445903   

          6           7           8           9    ...         400  \
0  138.487131  157.783370  212.575480  138.757157  ...  127.299674   
1   80.434100  120.632207  246.703324   85.359354  ...   68.563284   
2   74.519506  114.123728  249.092381   78.200821  ...   54.480651   

          401         402         403         404         405         406  \
0  128.878661  128.899471  124.575693  126.782222  125.882560  122.172199   
1   70.656760   70.458550   71.595316   72.018237   70.375030   69.695426   
2   58.566016   58.252614   58.973441   59.883368   56.854206   56.148569   

          407         408         409  
0  126.745268  126.771528  123.639124  
1   71.458322   77.723805   69.311660  
2   58.039558   66.475668   56.816833  

[3 rows x 410 columns]

In [82]:
distances.shape

(3, 410)

In [90]:
type(distances)

pandas.core.frame.DataFrame

In [84]:
magnitudes = vector_magnitude['magnitude'].apply(lambda row: pd.read_json(row, typ = 'list'))

In [95]:
type(magnitudes.iloc[1])

pandas.core.series.Series

In [86]:
magnitudes.shape

(410, 1)

In [96]:
type(magnitudes)

pandas.core.frame.DataFrame

In [108]:
magnitudes.to_numpy()

array([[list([[127.4188473234]])],
       [list([[67.6244639575]])],
       [list([[62.0654428818]])],
       [list([[143.2048138668]])],
       [list([[53.2455353861]])],
       [list([[46.6373914753]])],
       [list([[58.5571806358]])],
       [list([[105.5725344669]])],
       [list([[248.1236070731]])],
       [list([[62.7827711249]])],
       [list([[150.3658741472]])],
       [list([[79.7224374518]])],
       [list([[86.7795323135]])],
       [list([[130.6969114575]])],
       [list([[133.2632752841]])],
       [list([[174.0766796029]])],
       [list([[77.7718456771]])],
       [list([[221.9465839689]])],
       [list([[130.8099157291]])],
       [list([[166.5842859348]])],
       [list([[123.9461781888]])],
       [list([[143.63853033]])],
       [list([[84.9090632799]])],
       [list([[124.1266416915]])],
       [list([[87.2993855175]])],
       [list([[79.7147115956]])],
       [list([[108.120253388]])],
       [list([[119.472897368]])],
       [list([[73.5255182087]])],
  

In [88]:
p = pairwise_distances(magnitudes, metric='manhattan')

ValueError: setting an array element with a sequence.

In [ ]:
def get_euclidean_distance(local_id)

In [ ]:
def get_ts_ss_similarity(article_id):

In [ ]:
def get_triangle_similarity(magnitude, angles):

In [33]:
import numpy as np
from sklearn.metrics import pairwise_distances
from sklearn.metrics.pairwise import pairwise_kernels

X = np.array([[2, 3], [3, 5], [5, 8]])
Y = np.array([[1, 0], [2, 1]])

In [34]:
X

array([[2, 3],
       [3, 5],
       [5, 8]])

In [35]:
Y

array([[1, 0],
       [2, 1]])

In [36]:
pairwise_distances(Y, Y, metric='manhattan')

array([[0., 2.],
       [2., 0.]])

In [37]:
pairwise_distances(X, X, metric='manhattan')

array([[0., 3., 8.],
       [3., 0., 5.],
       [8., 5., 0.]])

In [32]:

pairwise_distances(X, Y, metric='manhattan')



pairwise_distances(X, metric='manhattan')



pairwise_kernels(X, Y, metric='linear')

array([[ 2.,  7.],
       [ 3., 11.],
       [ 5., 18.]])

In [59]:
p = np.array([[1,2,5], [2,3,4], [1,2,9]])
p

array([[1, 2, 5],
       [2, 3, 4],
       [1, 2, 9]])

In [60]:
p.shape

(3, 3)

In [61]:
pairwise_distances(p, metric='manhattan')

array([[0., 3., 4.],
       [3., 0., 7.],
       [4., 7., 0.]])

In [62]:
pairwise_kernels(p, metric='linear')

array([[30., 28., 50.],
       [28., 29., 44.],
       [50., 44., 86.]])

In [66]:
Y

array([[1, 0],
       [2, 1]])

In [64]:
np.square(Y)

array([[1, 0],
       [4, 1]])

In [100]:
df = pd.DataFrame({"A": [1, 2], "B": [3, 4]})
type(df)

pandas.core.frame.DataFrame

In [101]:
df.to_numpy()

array([[1, 3],
       [2, 4]])